export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_GLOBAL_QUIZ_LIST = 'GET_GLOBAL_QUIZ_LIST';
export const GET_QUESTIONS_QUIZ = 'GET_QUESTIONS_QUIZ';
export const SET_CURRENT_PLAY_QUIZ = 'SET_CURRENT_PLAY_QUIZ';
export const SET_CURRENT_PLAY_QUIZ_QUESTION = 'SET_CURRENT_PLAY_QUIZ_QUESTION';
export const SET_CURRENT_PLAY_QUIZ_ANSWER = 'SET_CURRENT_PLAY_QUIZ_ANSWER';

export const ADD_PLAY_ANSWER = 'ADD_PLAY_ANSWER';
export const ADD_PLAY_ANSWER_SUCCESS = 'ADD_PLAY_ANSWER_SUCCESS';

export const GET_ANSWERS_PLAYER = 'GET_ANSWERS_PLAYER';
export const GET_ANSWERS_PLAYER_SUCCESS = 'GET_ANSWERS_PLAYER';

export const ADD_QUIZ = 'ADD_QUIZ';
export const ADD_QUIZ_SUCCESS = 'ADD_QUIZ_SUCCESS';

export const SET_CURRENT_QUIZ_PLAYED = 'SET_CURRENT_QUIZ_PLAYED';